theme: jekyll-theme-architect

title: [tck_jafv2_0]
description: [Technology Compatibility Kit User's Guide for Jakarta Activation 2.0 for Technology Vendors, Release 2.0]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/jaf-tck
  download: https://github.com/eclipse-ee4j/jaf-tck/releases
  #mailinglist: https://javaee.groups.io/g/tck_jaxrs_v2_1
  #javadocs:
  #docs: https://javaee.github.io/tck_jaxrs_v2_1
  #faq:

